name: 'Validate the code'

pr:
    - master
    - develop

pool:
    vmImage: 'ubuntu-latest'
    demands:
        - npm

steps:
    - task: Npm@1
      displayName: 'Install node modules'
      inputs:
          verbose: false

    - script: npm run types:check
      displayName: 'Check Types with TypeScript'

    - script: npm run format:check
      displayName: 'Check Format with Prettier'

    - script: npm run lint
      displayName: 'Run Linter'

    - script: npm run build
      displayName: 'Build Application'

    - script: npm run test:coverage
      displayName: 'Run Unit Tests'
